### ISSUE TITLE
Date/Time Listing does not work on Safari

### ISSUE THREAD

**Issue by Tempus** [Zamiell/isaac-racing-server#8]
Line 11 of race.js
`dt = new Date($(this).find("#racedate").eq(0).html());`

Produces an invalid Date object on Safari. This leads to a result of 
`undefined, undefined NaNth, NaN:NaN`
after line 37 edits the date info.

This is because the Date info is not ISO-8601 compliant - Safari is strict and Chrome is not strict about this. You can find a fix for the particular error [here](https://stackoverflow.com/questions/21883699/safari-javascript-date-nan-issue-yyyy-mm-dd-hhmmss).

It basically amounts to adding `.replace(/\s/, 'T')` to your datestring retrieved.

**Comment by sillypears** [comment]
As far as I remember we aren't passing it as an 8601 datestring. I just verified and it is ` 2017-08-15 19:31:43 +0000 UTC` which is then being pushed into the date constructor. This is what gets pushed out of the database from golang. It's grabbing a []uint8 and saving it time.Time, so if you have a better way of handling that let me know, otherwise I'll look into it further.

**Comment by sillypears** [comment]
@Tempus Okay I think I fixed it by doing the following hack

`dt = new Date($(this).find("#racedate").eq(0).html().replace(/\s/, '').replace(/\s/, 'T').replace(' +0000 UTC', ''));`

**Comment by Zamiell** [comment]
From Discord:
```
Chronometrics - Last Wednesday at 11:52 PM
Nope
Still the same issue
If I step through it in js, the original race listing is
2017-09-07 00:59:37 +0000 UTC
But when it runs through
dt = new Date($(this).find("#racedate").eq(0).html());
The Date object is invalid, so the output formatting just returns junk
```

**Comment by Zamiell** [comment]
fixed
